name: Flood Detection CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment for linting/testing
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # # Run Unit Tests (if you have any tests)
    # - name: Run Tests
    #   run: |
    #     pytest tests/

    # Log in to Docker Hub (optional)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t flood-prediction:latest .

    # Run the Docker container
    - name: Run Docker Container
      run: docker run --rm -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} flood-prediction:latest
